### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by momspaghetti123** [MayouKurayami/KoikatuVRAssistPlugin#1]
Thank you for your mods, they work great. I've compiled the fresh KK_Ahegao plugin.

I see you have some nice fixes on this plugin, are you planning to do a release at some point? I've tried to manually compile but seems you got some NuGet stuff.

Thanks.

**Comment by MayouKurayami** [comment]
Yes, there will be a new release, eventually.
I am still working on more integrations between KoikatuVRAssistPlugin and my other plugins, but that requires rewriting parts of those plugins and progress is a bit stalled right now.

In the meantime, if you want to compile this yourself, I've just pushed the missing _nuget.config_ so you should be able to get most references via nuget with the exception of Assembly-CSharp.
For that you'd need to manually point it to the VR version because believe it or not, it's still not on nuget.

**Comment by momspaghetti123** [comment]
Thanks!
